SELECT
    c.name AS category_name,
    COUNT(fc.film_id) AS film_count
FROM
    film_category AS fc
JOIN
    category AS c ON fc.category_id = c.category_id
GROUP BY
	c.name;
#List the Number of Films Per Category
SELECT
    s.store_id,
    ci.city,
    co.country
FROM
    store AS s
JOIN
    address AS a ON s.address_id = a.address_id
JOIN
    city AS ci ON a.city_id = ci.city_id
JOIN
    country AS co ON ci.country_id = co.country_id;
#Retrieve the Store ID, City, and Country for Each Store
SELECT
	s.store_id,
	SUM(p.amount) AS total_reveneu
FROM
	payment AS p
JOIN
    rental AS r ON p.rental_id = r.rental_id
JOIN
    inventory AS i ON r.inventory_id = i.inventory_id
JOIN
    store AS s ON i.store_id = s.store_id
GROUP BY 
	s.store_id;
# Calculate the Total Revenue Generated by Each Store in Dollars
SELECT
	c.name AS category_name,
    AVG(f.length) AS average_length
FROM
    film AS f
JOIN
    film_category AS fc ON f.film_id = fc.film_id
JOIN 
	category AS c ON fc.category_id = c.category_id
GROUP BY
	c.name;
#Determine the Average Running Time of Films for Each Category